### ISSUE TITLE
Auth should maybe use NIP-42 for auth?

### ISSUE THREAD

**Issue by wbobeirne** [fedibtc/LN-GPT#10]
<img src="https://github.com/fedibtc/LN-GPT/assets/649992/5796fecb-96ae-4249-9b8c-b5486cd53145" width="300" />

Got a report in the Fedi app that this message was confusing. I think I've seen other apps use NIP-42 for auth, but maybe there's a more standard one for signing in with nostr. But ideally it uses a `kind` that is clearly authentication, so that our app can just say that it's an auth request.

Low priority.

**Comment by wbobeirne** [comment]
Original bug report: https://www.notion.so/fedi21/Bug-report-57bf8d0c-c3139cd9e08341379c6fe9bc88298cda?pvs=4

**Comment by IroncladDev** [comment]
LNGPT uses 22242, which is the auth protocol
