### ISSUE TITLE
Success screen text should wrap

### ISSUE THREAD

**Issue by wbobeirne** [fedibtc/LN-GPT#3]
This may be an issue more for the UI library than this particular instance, but Obi reported this during the feedback testing. But this text should wrap rather than bleed out of the circle.

<img src="https://github.com/fedibtc/LN-GPT/assets/649992/3add1628-cb15-4dd8-b760-66bccb031c5a" width="250" />

**Comment by IroncladDev** [comment]
Not sure how to make text wrap in a circular container. For now I shortened the text to be "Topup Successful".

**Comment by wbobeirne** [comment]
Technically that can be done via [`shape-outside`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-outside) but that's totally overkill, no need to do that. Just adding some padding to the text or the container of the text to avoid the first line should be fine.
