### ISSUE TITLE
EU collect length failure

### ISSUE THREAD

**Issue by wbobeirne** [fedibtc/LN-GPT#5]
Originally reported by Obi here: https://www.notion.so/fedi21/fcee02514ee44f2d86dcda14885569b9?v=545fef24226e4ff49e39089cf1dd0e60&p=1e051590485040c0812f760e82b24af6&pm=s

> LNGPT is failing to respond to queries due to an issue eu collect length.

Not sure what this means, feel free to follow up with him directly for more info.

**Comment by IroncladDev** [comment]
This was fixed in a previous commit after multiple users reported the token length overflowing.
